#!/bin/bash
# Update manifest.json with all pieces in the pieces directory
# Run after each email script to register new pieces

SITE_DIR="$(cd "$(dirname "$0")" && pwd)"
PIECES_DIR="$SITE_DIR/pieces"
MANIFEST="$PIECES_DIR/manifest.json"

# Build the pieces array
pieces=""
for file in "$PIECES_DIR"/*.html; do
    if [[ -f "$file" ]]; then
        filename=$(basename "$file")
        # Extract date and type from filename: YYYY-MM-DD-type.html
        date=$(echo "$filename" | grep -oE '^[0-9]{4}-[0-9]{2}-[0-9]{2}')
        type=$(echo "$filename" | sed 's/^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-//' | sed 's/\.html$//')

        if [[ -n "$date" && -n "$type" ]]; then
            # Get file modification time as timestamp for sorting
            timestamp=$(stat -f "%m" "$file" 2>/dev/null || stat -c "%Y" "$file" 2>/dev/null || echo "0")
            if [[ -n "$pieces" ]]; then
                pieces="$pieces,"
            fi
            pieces="$pieces
    {\"file\": \"$filename\", \"date\": \"$date\", \"type\": \"$type\", \"timestamp\": $timestamp}"
        fi
    fi
done

# Write manifest
cat > "$MANIFEST" << EOF
{
  "pieces": [$pieces
  ]
}
EOF

echo "Manifest updated: $(echo "$pieces" | grep -c 'file') pieces"

# Push to GitHub for Cloudflare auto-deploy
cd "$SITE_DIR"
if git status --porcelain | grep -q .; then
    . "$HOME/Documents/Vaults/_meta/services/git-lock.sh"
    locked_commit_push "$SITE_DIR" "feat: add $(date +%Y-%m-%d) pieces

Auto-generated by ambient email system" 2>/dev/null && echo "Pushed to GitHub" || echo "Push failed (offline?)"
fi
